#!/usr/bin/env node
/**
 * download-covers.js
 * Downloads all Notion game cover images locally and writes js/cover-manifest.js.
 *
 * Usage:
 *   NOTION_TOKEN=your_token node scripts/download-covers.js
 *
 * Or create a .env file in the project root with:
 *   NOTION_TOKEN=your_token
 * Then run:
 *   node scripts/download-covers.js
 */

const fs   = require("fs");
const path = require("path");

// Simple .env loader — no dependencies needed
const envPath = path.join(__dirname, "..", ".env");
if (fs.existsSync(envPath)) {
  fs.readFileSync(envPath, "utf8").split("\n").forEach(line => {
    const [k, ...v] = line.split("=");
    if (k && v.length && !process.env[k.trim()]) {
      process.env[k.trim()] = v.join("=").trim();
    }
  });
}

const DATABASE_ID  = "3a7ccf9e-b5b8-40de-ab98-c01372ca894a";
const COVERS_DIR   = path.join(__dirname, "..", "assets", "images", "covers");
const MANIFEST_OUT = path.join(__dirname, "..", "js", "cover-manifest.js");
const TOKEN        = process.env.NOTION_TOKEN;

if (!TOKEN) {
  console.error("✖  NOTION_TOKEN is not set.");
  console.error("   Add it to a .env file or set it in your environment.");
  process.exit(1);
}

function toSlug(title) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function extFromContentType(ct, url) {
  if (ct?.includes("png"))  return ".png";
  if (ct?.includes("webp")) return ".webp";
  if (ct?.includes("gif"))  return ".gif";
  const m = url.split("?")[0].match(/\.(png|jpg|jpeg|webp|gif)$/i);
  if (m) return "." + m[1].toLowerCase().replace("jpeg", "jpg");
  return ".jpg";
}

async function fetchAllGames() {
  const games = [];
  let cursor  = undefined;
  let hasMore = true;

  process.stdout.write("Fetching game list from Notion");
  while (hasMore) {
    process.stdout.write(".");
    const body = {
      filter:    { property: "Status", select: { equals: "Complete" } },
      page_size: 100,
    };
    if (cursor) body.start_cursor = cursor;

    const res  = await fetch(`https://api.notion.com/v1/databases/${DATABASE_ID}/query`, {
      method:  "POST",
      headers: {
        Authorization:    "Bearer " + TOKEN,
        "Notion-Version": "2022-06-28",
        "Content-Type":   "application/json",
      },
      body: JSON.stringify(body),
    });

    if (!res.ok) {
      console.error(`\n✖  Notion API error: ${res.status}`);
      process.exit(1);
    }

    const data = await res.json();
    for (const page of data.results) {
      const title    = page.properties.title?.title?.[0]?.plain_text || "";
      const coverUrl = page.cover?.external?.url || page.cover?.file?.url || null;
      if (title && coverUrl) {
        games.push({ slug: toSlug(title), title, coverUrl });
      }
    }
    hasMore = data.has_more;
    cursor  = data.next_cursor;
  }
  console.log(` ${games.length} games found.\n`);
  return games;
}

async function downloadImage(url, dest) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const buf = await res.arrayBuffer();
  fs.writeFileSync(dest, Buffer.from(buf));
}

async function main() {
  if (!fs.existsSync(COVERS_DIR)) fs.mkdirSync(COVERS_DIR, { recursive: true });

  const games    = await fetchAllGames();
  const manifest = {};
  let downloaded = 0;
  let skipped    = 0;
  let failed     = 0;

  for (const game of games) {
    process.stdout.write(`  ${game.title.padEnd(40)}`);

    // Detect extension from a HEAD request
    let ext = ".jpg";
    try {
      const head = await fetch(game.coverUrl, { method: "HEAD" });
      ext = extFromContentType(head.headers.get("content-type"), game.coverUrl);
    } catch { /* keep .jpg */ }

    const filename = game.slug + ext;
    const dest     = path.join(COVERS_DIR, filename);
    const webPath  = `assets/images/covers/${filename}`;

    if (fs.existsSync(dest)) {
      console.log("↩  already cached");
      manifest[game.slug] = webPath;
      skipped++;
      continue;
    }

    try {
      await downloadImage(game.coverUrl, dest);
      manifest[game.slug] = webPath;
      console.log("✔  saved");
      downloaded++;
    } catch (err) {
      console.log(`✖  failed (${err.message})`);
      failed++;
    }
  }

  // Write manifest
  const lines = [
    "/* Auto-generated by scripts/download-covers.js — do not edit manually */",
    "/* Run: node scripts/download-covers.js  to refresh */",
    "var COVER_IMAGES = " + JSON.stringify(manifest, null, 2) + ";",
  ];
  fs.writeFileSync(MANIFEST_OUT, lines.join("\n") + "\n");

  console.log(`
─────────────────────────────────────────
  Downloaded : ${downloaded}
  Skipped    : ${skipped} (already cached)
  Failed     : ${failed}
  Manifest   : js/cover-manifest.js
─────────────────────────────────────────`);

  if (failed > 0) {
    console.log("  Re-run the script to retry failed images.");
  }
}

main().catch(err => {
  console.error("Fatal:", err.message);
  process.exit(1);
});
